-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 24-Jan-2022 às 21:22
-- Versão do servidor: 10.4.17-MariaDB
-- versão do PHP: 8.0.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `streaming`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `filmes`
--

CREATE TABLE `filmes` (
  `id` int(11) NOT NULL,
  `titulo` text NOT NULL,
  `ano` text NOT NULL,
  `idade` text NOT NULL,
  `descricao` text NOT NULL,
  `trailer` text NOT NULL,
  `foto1` text NOT NULL,
  `foto2` text NOT NULL,
  `categoria` text NOT NULL,
  `popular` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Extraindo dados da tabela `filmes`
--

INSERT INTO `filmes` (`id`, `titulo`, `ano`, `idade`, `descricao`, `trailer`, `foto1`, `foto2`, `categoria`, `popular`) VALUES
(1, 'Peaky Blinders', '2013', '+16', 'Peaky Blinders is a British period crime drama television series created by Steven Knight. Set in Birmingham, England, the series follows the exploits of the Peaky Blinders crime gang in the direct aftermath of the First World War. The fictional gang is loosely based on a real urban youth gang of the same name, who were active in the city from the 1890s to the early 20th century. Peaky Blinders features an ensemble cast, led by Cillian Murphy, Helen McCrory, and Paul Anderson, starring as Tommy Shelby, Elizabeth \"Polly\" Gray, and Arthur Shelby, respectively, the gang\'s senior members. Sam Neill, Iddo Goldberg, Tom Hardy, Paddy Considine, Adrien Brody, Aidan Gillen, Annabelle Wallis, Charlotte Riley, Sam Claflin, Stephen Graham, and Anya Taylor-Joy also have recurring roles at various times of the series. The show premiered on 12 September 2013, telecast on BBC Two until the fourth series, and then shifted to BBC One for the fifth and upcoming sixth series.            ', 'PeakyBlinders.mp4', 'popular_peaky.png', 'peakyBlinders_info.jpg', 'populares', 1),
(2, 'The 100', '2014', '+14', 'Na série The 100, quando uma guerra nuclear destruiu a civilização e o planeta Terra, os únicos sobreviventes foram 400 pessoas que estavam em 12 estações espaciais em órbita. 97 anos e três gerações depois, a população já contava com 4 mil pessoas, mas os recursos já vão escassos. Para garantir o futuro, um grupo de cem jovens é enviado à superfície da Terra para descobrir se ela está habitável. Com a sobrevivência da raça humana em suas mãos, estes jovens precisam superar suas diferenças e unir forças para cruzar juntos o seu caminho.', 'the100.mp4', 'popular_the100.png', 'the100_infoo.jpg', 'populares', 1),
(3, 'Dont Look Up', '2021', '+16', 'Dois astrônomos medíocres descobrem que em poucos meses um meteorito destruirá o planeta Terra. A partir desse momento, eles devem alertar a humanidade por meio da imprensa sobre o perigo que se aproxima.', 'dontlookup.mp4', 'popular_dontlook.png', 'dontlook_info.png', 'populares', 1),
(4, 'Jumanji', '2017', '+17', 'Alan Parrish desapareceu quando era menino e ninguém acredita na história de seu amigo de que ele foi sugado por um jogo de tabuleiro. Vinte e seis anos depois, duas crianças acham o jogo no sótão e, quando começam a jogar, Alan é libertado. Mas a disputa ainda não acabou e Alan precisa terminar antes de ser realmente solto.', 'JUMANJI.mp4', 'popular_jumanji.png', 'jumanji_info.png', 'populares', 1),
(5, 'Venom', '2018', '+18', 'O jornalista Eddie Brock desenvolve força e poder sobre-humanos quando seu corpo se funde com o alienígena Venom. Dominado pela raiva, Venom tenta controlar as novas e perigosas habilidades de Eddie.', 'venom.mp4', 'popular_venom.png', 'venom_info.png', 'populares', 1),
(6, 'Ronaldo', '2015', '+6', 'Filmado ao longo de 14 meses com acesso sem precedentes ao círculo restrito do homem e do esporte, este é o primeiro filme oficial e autorizado do jogador português Cristiano Ronaldo, uma das figuras mais célebres do futebol. Pela primeira vez, o mundo tem acesso imparcial e inédito ao atacante, através de conversas profundas, filmagens fantásticas de jogos e vídeos de arquivo jamais vistos antes.', 'Ronaldo.mp4', 'doc_ronaldo.png', 'ronaldo_info.png', 'documentarios', 0),
(7, 'The Last Dance', '2020', '+6', 'Esta série documental relata a ascensão da superestrela Michael Jordan e dos Chicago Bulls dos anos 90, através de imagens inéditas da época de 1997/1998. Veja tudo o que quiser. A série que segue Michael Jordan, Phil Jackson e outros no seu auge \'encestou\' o Emmy de Melhor Série Documental.', 'lastDance.mp4', 'doc_basket.png', 'lastdance_info.png', 'documentarios', 0),
(8, 'The Notorious Big: I Got a Story to Tell', '2021', '+14', 'The Notorious B.I.G., um dos grandes ícones do hip-hop, nasceu Christopher Wallace. Imagens raras e depoimentos de familiares e amigos ajudam a apresentar o homem por trás da lenda.', 'Biggie.mp4', 'doc_notorious.png', 'biggie_info.png', 'documentarios', 0),
(9, 'Schumacher', '2021', '+6', 'No filme, tanto a esposa Corinna Schumacher quanto os filhos Gina e Mike dão depoimentos inéditos sobre a condição de saúde atual de Schumacher. ... Antes de se aposentar como heptacampeão em 2012, Schumacher venceu 91 Grandes Prêmios de F1. Somente em 2020, com Lewis Hamilton, o recorde do alemão foi quebrado.', 'Schumacher.mp4', 'doc_f1.png', 'schumacher_info.png', 'documentarios', 0),
(10, 'Britney vs Spears', '2021', '+12', 'Britney Vs. Spears é um documentário sobre a cantora pop Britney Spears onde ela vai contar sobre sua fama, carreira, depressão, sua ascensão ainda criança e a saída dos braços de seu pai conservatório com o movimento #freebritney.', 'PeakyBlinders.mp4', 'doc_britney.png', 'britney_info.png', 'documentarios', 0),
(11, 'Keeping Up with the Kardashians', '2007', '+12', 'Keeping Up with the Kardashians (abreviado como KUWTK) é uma série de reality show americano que vai ao ar no canal pago E!. O programa foca nas vidas profissionais e pessoais da família Kardashian. Sua premissa originou-se de Ryan Seacrest, que também atua como produtor executivo. A série estreou em 14 de outubro de 2007 e tornou-se posteriormente uma das séries de reality show mais longa no país. A vigésima e última temporada estreiou em 18 de março de 2021.', 'kardashians.mp4', 'reality_kardashians.png', 'kardashians_info.png', 'reality', 0),
(12, 'Too Hot to Handle', '2020', '+18', 'Too Hot to Handle é um reality show de namoro de televisão produzido pela produtora britânica Fremantle Talkback. O programa consistiu em oito episódios, todos lançados em 17 de abril de 2020 pela Netflix. A apresentadora da série é uma assistente virtual chamada \"Lana\", que dá ao elenco as regras que eles devem seguir para a temporada; Desiree Burch é responsável pela narração do reality. A premissa do programa é ensinar jovens, solteiros, a criar conexões genuínas em vez de suas conversas habituais. Se os participantes se envolverem em qualquer contato sexual na ilha, o prêmio em dinheiro diminuirá, começando em 100 mil dólares.', 'TooHotToHandle.mp4', 'reality_toohot.png', 'toohottohandle_info.png', 'reality', 0),
(13, 'Hell\'s Kitchen', '2005', '+16', 'Essa é a produção original do reality show britânico \"Hell\'s Kitchen\", em que famosos que não sabem nada de cozinha recebem a orientação (e as duras críticas) de Marco Pierre White, um gênio da gastronomia que, no auge de sua carreira, assumiu o comando do programa. A cada semana, os competidores se esforçam para mostrar o melhor de si e conquistarem o prêmio no final da temporada. A série começou no primeiro ano (em 2004) com Gordon Ramsay, que mais tarde assumiu o comando da versão americana de \"Hell\'s Kitchen\", a qual apresenta até hoje. No segundo ano, os candidatos foram liderados pelos chefs Gary Rhodes e Jean-Christophe Novelli, e finalmente, a partir da terceira temporada, Marco Pierre White assumiu o comando do programa.', 'HellsKitchen.mp4', 'reality_hells.png', 'hells_info.png', 'reality', 0),
(14, 'Jersey Shore\r\n', '2009', '+18', 'Jersey Shore é um reality show produzido pela MTV norte-americana que segue oito pessoas que moram em uma mesma casa, seguindo seus afazeres diários na costa do estado de Nova Jersey, nos Estados Unidos. O programa foi filmado em agosto de 2009 em Seaside Heights, New Jersey, mas também houve filmagens em lugares como Toms River, Neptune Township e Atlantic City. O programa começou em meio a controvérsias, pois o uso da palavra \"Guido/Guidette\", gíria associada a ítalo-americanos, sendo que os integrantes do grupo não eram residentes da região, um reduto de italianos nos EUA. A música tema tocada no inicio do programa é \"Get Crazy\" da banda LMFAO.', 'JerseyShore.mp4', 'reality_jersey.png', 'jersey_info.png', 'reality', 0),
(15, 'America\'s Got Talent', '2006', '+6', 'America\'s Got Talent (também conhecido como AGT) é uma série de televisão estadunidense exibida pela NBC, e parte da série global Britain\'s Got Talent, criado por Simon Cowell. É um show de talentos que apresenta cantores, dançarinos, mágicos, humoristas e outros artistas de todas as idades concorrendo para o prêmio de US$ 1 milhão. O espetáculo estreou em junho de 2006 para a Temporada de Verão. Começando na terceira temporada, o prêmio máximo incluía US$ 1 milhão e um show como destaque na Las Vegas Strip.', 'AGT.mp4', 'reality_americans.png', 'agt_info.png', 'reality', 0),
(16, 'Enola Holmes', '2020', '+14', '\"Quando sua mãe desaparece em seu aniversário de 16 anos, Enola procura a ajuda de seus irmãos mais velhos. Mas assim que ela percebe que eles estão menos interessados em resolver o caso do que mandá-la para o internato, Enola faz a única coisa que uma garota esperta, cheia de recursos e destemida em 1880 faria. Ela foge para Londres para encontrá-la. Encontrando diversos personagens memoráveis pelo caminho, Enola se acha no meio de uma conspiração que pode alterar o rumo da história política\".', 'EnolaHolmes.mp4', 'familia_enola.png', 'enola_info.png', 'familia', 0),
(17, 'Karate Kid', '1984', '+12', 'The Karate Kid é um filme de artes marciais e drama romântico norte-americano de 1984 do diretor John G. Avildsen e escrito por Robert Mark Kamen, estrelado por Ralph Macchio e Noriyuki \"Pat\" Morita e Elisabeth Shue. É uma história underdog no molde de um sucesso anterior de Avildsen de 1976, o filme Rocky. O filme conta a história de um jovem lutador que deseja aprender caratê, e para isso convence um experiente mestre a lhe dar aulas, que acabam por transformar-se em lições de vida.', 'TheKarateKid.mp4', 'familia_karate.png', 'karatekid_info.png', 'familia', 0),
(18, 'Jurassic Park', '1993', '+18', 'Os paleontólogos Alan Grant, Ellie Sattler e o matemático Ian Malcolm fazem parte de um seleto grupo escolhido para visitar uma ilha habitada por dinossauros criados a partir de DNA pré-histórico. O idealizador do projeto e bilionário John Hammond garante a todos que a instalação é completamente segura. Mas após uma queda de energia, os visitantes descobrem, aos poucos, que vários predadores ferozes estão soltos e à caça.', 'JurassicPark.mp4', 'familia_jurassic.png', 'jurassic_info.png', 'familia', 0),
(19, 'Indiana Jones', '1981', '+16', 'O arqueólogo Indiana Jones precisa encontrar a Arca da Aliança, uma relíquia bíblica que contém os dez mandamentos. Como o portador do artefato se torna invencível, os nazistas também vão fazer de tudo para adquirir esse precioso objeto.', 'IndianaJones.mp4', 'familia_indiana.png', 'indiana_info.png', 'familia', 0),
(20, 'Spider Man: Homecoming', '2017', '+12', 'Depois de lutar ao lado dos Vingadores, chegou a hora do jovem Peter Parker voltar para casa em Nova York ao lado de sua tia May. Sob o olhar atento do mentor Tony Stark, Peter começa a abraçar sua nova identidade como Homem-Aranha e combate diariamente pequenos crimes nas redondezas. Ele acredita que encontrou a missão de sua vida quando o terrível vilão Abutre surge ameaçando a cidade. O problema é que a tarefa não será tão fácil como ele imaginava.', 'Spider-Man_ Homecoming.mp4', 'familia_spider.png', 'homecoming_info.png', 'familia', 0),
(21, 'The Dark Knight', '2008', '+15', 'Com a ajuda de Jim Gordon e Harvey Dent, Batman tem mantido a ordem na cidade de Gotham. Mas um jovem e anárquico criminoso conhecido como Coringa ganha força e decide instaurar um verdadeiro caos na cidade. O justiceiro será testado psicologicamente e fisicamente como nunca fora antes em um confronto bastante pessoal. Cabe a Batman encontrar uma maneira de deter o sádico vilão antes que mais vidas sejam perdidas.', 'TheDarkKnight.mp4', 'filme_acao1.png', 'darknight_info.png', 'filmes_acao', 0),
(22, 'The Matrix', '1999', '+14', 'Um jovem programador é atormentado por estranhos pesadelos nos quais sempre está conectado por cabos a um imenso sistema de computadores do futuro. À medida que o sonho se repete, ele começa a levantar dúvidas sobre a realidade. E quando encontra os misteriosos Morpheus e Trinity, ele descobre que é vítima do Matrix, um sistema inteligente e artificial que manipula a mente das pessoas e cria a ilusão de um mundo real enquanto usa os cérebros e corpos dos indivíduos para produzir energia.', 'TheMatrix.mp4', 'filme_acao2.png', 'matrix_info.png', 'filmes_acao', 0),
(23, 'Spider Man', '2002', '+12', 'Depois de ser picado por uma aranha geneticamente modificada em uma demonstração científica, o jovem nerd Peter Parker ganha superpoderes. Inicialmente, ele pretende usá-los para para ganhar dinheiro, adotando o nome de Homem-Aranha e se apresentando em lutas de exibição. Porém, ao presenciar o assassinando de seu tio Ben e sentir-se culpado, Peter decide não mais usar seus poderes para proveito próprio e sim para enfrentar o mal, tendo como seu primeiro grande desafio o psicótico Duende Verde.', 'Spider-Man1.mp4', 'filme_acao4.png', 'spiderman1_info.png', 'filmes_acao', 0),
(24, 'Inception', '2010', '+16', 'Dom Cobb é um ladrão com a rara habilidade de roubar segredos do inconsciente, obtidos durante o estado de sono. Impedido de retornar para sua família, ele recebe a oportunidade de se redimir ao realizar uma tarefa aparentemente impossível: plantar uma ideia na mente do herdeiro de um império. Para realizar o crime perfeito, ele conta com a ajuda do parceiro Arthur, o discreto Eames e a arquiteta de sonhos Ariadne. Juntos, eles correm para que o inimigo não antecipe seus passos.', 'Inception.mp4', 'filme_acao5.png', 'inception_info.png', 'filmes_acao', 0),
(25, 'Parasite', '2019', '+14', 'Toda a família de Ki-taek está desempregada, vivendo em um porão sujo e apertado, mas uma obra do acaso faz com que ele comece a dar aulas de inglês a uma garota de família rica. Fascinados com a vida luxuosa destas pessoas, pai, mãe e filhos bolam um plano para se infiltrarem também na família burguesa, um a um. No entanto, os segredos e mentiras necessários à ascensão social custam caro a todos.', 'Parasite.mp4', 'filme_suspense1.png', 'parasite_info.png', 'filmes_suspense', 0),
(26, 'Se7en: Os Sete Pecados Mortais', '1995', '+16', 'A ponto de se aposentar, o detetive William Somerset pega um último caso, com a ajuda do recém-transferido David Mills. Juntos, descobrem uma série de assassinatos e logo percebem que estão lidando com um assassino que tem como alvo pessoas que ele acredita representar os sete pecados capitais.', 'Se7en.mp4', 'filme_suspense2.png', 'seven_info.png', 'filmes_suspense', 0),
(27, 'The Prestige', '2006', '+16', 'No século 19, em Londres, dois amigos ilusionistas e mágicos, Alfred Borden e Rupert Angier, acabam construindo uma rivalidade, uma batalha por supremacia, que se estende ao longo dos anos e que se transforma em obsessão, cujos resultados serão inevitavelmente trágicos.', 'THEPRESTIGE.mp4', 'filme_suspense3.png', 'theprestige_info.png', 'filmes_suspense', 0),
(28, 'The Departed', '2006', '+18', 'Billy Costigan, um jovem policial, recebe a missão de se infiltrar na máfia, no grupo comandado por Frank Costello. Billy conquista sua confiança ao mesmo tempo em que Colin Sullivan, um criminoso que atuou na polícia como informante de Costello, também ascende dentro da corporação. Tanto Billy quanto Colin se sentem aflitos devido à vida dupla que levam. Mas, quando a máfia e a polícia descobrem que há um espião entre eles, a vida de ambos passa a correr perigo.', 'TheDeparted.mp4', 'filme_suspense4.png', 'TheDeparted_info.png', 'filmes_suspense', 0),
(29, 'Scream', '1996', '+18', 'Um grupo de jovens enfrenta um assassino mascarado que testa seus conhecimentos sobre filmes de terror. A pequena cidade de Woodsboro nunca mais será a mesma.', 'Scream.mp4', 'filme_terror1.png', 'scream_info.png', 'filmes_terror', 0),
(30, 'Last Night in Soho', '2021', '+18', 'Uma aspirante a designer de moda misteriosamente viaja no tempo para os anos 1960. No entanto, ela logo descobre que o glamour da época esconde algo sombrio.', 'LASTNIGHTINSOHO.mp4', 'filme_terror3.png', 'lastnight_info.png', 'filmes_terror', 0),
(31, 'Antlers', '2021', '+18', 'Uma professora da cidade de Oregon (Keri Russell) e seu irmão, o xerife local (Jesse Plemons), descobrem que um jovem estudante está mantendo um segredo perigoso, com consequências assustadoras. Dirigido por Scott Cooper e produzido por Guillermo del Toro.', 'Antlers.mp4', 'filme_terror4.png', 'antlers_info.png', 'filmes_terror', 0),
(32, 'Midsommar', '2019', '+18', 'Após vivenciar uma tragédia pessoal, Dani vai com o namorado Christian e um grupo de amigos até a Suécia para participar de um festival local de verão. Mas, ao invés das férias tranquilas com a qual todos sonhavam, o grupo se depara com rituais bizarros de uma adoração pagã.\r\n', 'MIDSOMMAR.mp4', 'filme_terror5.png', 'midsommar_info.png', 'filmes_terror', 0),
(33, 'Encanto', '2021', '+6', 'Encanto da Walt Disney Animation Studios conta a história dos Madrigal, uma família extraordinária que vive escondida nas montanhas da Colômbia, em uma casa mágica, em uma cidade vibrante, em um lugar maravilhoso conhecido como um Encanto. A magia deste Encanto abençoou todos os meninos e meninas da família com um dom único, desde superforça até o poder de curar. Todos, exceto Mirabel. Mas, quando ela descobre que a magia que cerca o Encanto está em perigo, Mirabel decide que ela, a única Madrigal sem poderes mágicos, pode ser a última esperança de sua família excepcional', 'Encanto.mp4', 'filme_animacao1.png', 'encanto_info.png', 'filmes_animacao', 0),
(34, 'Moana', '2016', '+6', 'Uma jovem parte em uma missão para salvar seu povo. Durante a jornada, Moana conhece o outrora poderoso semideus Maui, que a guia em sua busca para se tornar uma mestre em encontrar caminhos. Juntos, eles navegam pelo oceano em uma viagem incrível.\r\n', 'Moana.mp4', 'filme_animacao3.png', 'moana_info.png', 'filmes_animacao', 0),
(35, 'Cinderela', '2015', '+6', 'A história acompanha a jovem Ella, cujo pai comerciante se casa novamente depois de ficar viúvo de sua mãe. Ansiosa para apoiá-lo, ela recebe bem a madrasta e suas filhas, Anastasia e Drisella, na nova casa. No entanto, quando seu pai morre subitamente, ela se vê à mercê de uma família cruel e invejosa. Trabalhando como empregada e agora chamada de Cinderela, ela começa a perder a esperança, mas uma fada madrinha provoca uma mudança em seu destino.', 'Cinderella.mp4', 'filme_animacao4.png', 'cinderela_info.png', 'filmes_animacao', 0),
(36, 'A Bela e o Monstro ', '2017', '+14', 'Moradora de uma pequena aldeia francesa, Bela tem o pai capturado pela Fera e decide entregar sua vida ao estranho ser em troca da liberdade do progenitor. No castelo, ela conhece objetos mágicos e descobre que a Fera é na verdade um príncipe que precisa de amor para voltar à forma humana.\r\n', 'BeautyandtheBeast.mp4', 'filme_animacao5.png', 'beautyandthebeast_info.png', 'filmes_animacao', 0),
(37, 'Pen 15', '2019', '+12', 'Histórias cómicas, vistas através dos olhos de duas mulheres adultas, que se representam a elas mesmas quando tinham 13 anos e andavam no 7º ano a tentar gerir a estranheza da adolescência.', 'PEN15.mp4', 'series_adolescentes1.png', 'pen15_info.png', 'series_adolescentes', 0),
(38, 'Rebelde', '2022', '+14', 'Continuação da novela mexicana Rebelde de Pedro Damián, a nova série da Netflix acompanha as vidas de um grupo de jovens estudantes do Elite Way School, um colégio privado frequentado pelos filhos da burguesia mexicana. Dentre dramas e muita música, surgirão paixões, amizades e rivalidades no caminho dos protagonistas.', 'Rebelde.mp4', 'series_adolescentes2.png', 'rebelde_info.png', 'series_adolescentes', 0),
(39, 'Runaways', '2010', '+16', 'Joan Jett e Cherie Currie, duas adolescentes rebeldes do sul da Califórnia, são as líderes das Runaways, a lendária banda que abriu o caminho para futuras gerações de mulheres roqueiras. Sob a influência do empresário Kim Fowley, a banda faz um grande sucesso. Porém, a relação tempestuosa entre as adolescentes ameaça o futuro do grupo.', 'Runaways.mp4', 'series_adolescentes3.png', 'runaaway_info.png', 'series_adolescentes', 0),
(40, 'Dare Me', '2020', '+14', 'Baseada na obra de Megan Abbott, a série mergulha no mundo cruel das líderes de torcida competitivas do ensino médio. A trama acompanha a relação tensa entre duas melhores amigos (Herizen Guardiola e Marlo Kelly) depois que um novo treinador (Willa Fitzgerald) chega para levar a equipe à excelência. Enquanto a amizade das meninas é colocada à prova, suas vidas mudam para sempre quando um crime chocante abala o mundo suburbano delas.', 'DAREME.mp4', 'series_adolescentes4.png', 'dareme_info.png', 'series_adolescentes', 0),
(41, 'All American', '2018', '+14', 'Inspirada pela vida do jogador de futebol americano Spencer Paysinger, essa série segue a jornada de um jogador de futebol americano de ensino médio em ascensão de Crenshaw, Los Angeles, que é recrutado para jogar para uma escola de Beverly Hills. Dois mundos completamente diferentes colidem quando duas famílias de lugares tão diferentes entram em conflito.', 'ALLAMERICAN.mp4', 'series_adolescentes5.png', 'allamerican_info.png', 'series_adolescentes', 0),
(42, 'Sherlock', '2010', '+12', 'O dr. John Watson precisa de um lugar para morar em Londres. Ele é apresentado ao detetive Sherlock Holmes e os dois acabam desenvolvendo uma parceria intrigante, na qual a dupla vagará pela capital inglesa solucionando assassinatos e outros crimes brutais. Tudo isso em pleno século XXI.', 'Sherlock.mp4', 'series_policiais1.png', 'sherlock_info.png', 'series_policiais', 0),
(43, 'Sons of Anarchy\r\n', '2008', '+16', 'Uma gangue de motoqueiros segue suas próprias leis e comanda, por debaixo dos panos, o tráfico de armas na região da aparentemente pacata da cidade de Charming, protegendo-a contra forasteiros hostis.', 'SonsofAnarchy.mp4', 'series_policiais2.png', 'sons_info.png', 'series_policiais', 0),
(44, 'Gotham', '2014', '+14', 'James Gordon (Ben McKenzie) é um detetive iniciante polícia. ... Com seu parceiro, o oficial Harvey Bullock (Donal Logue), Gordon conhece o único sobrevivente do assassinato: Bruce (David Mazuouz), um garoto de 12 anos, filho do casal, por quem ele imediatamente sente uma grande afeição.\r\n', 'GothamTrailer.mp4', 'series_policiais4.png', 'gotham_info.png', 'series_policiais', 0),
(45, 'O Justiceiro', '2017', '+14', 'O ex-marine Frank Castle só quer punir os criminosos responsáveis pela morte da sua família, mas torna-se alvo de uma conspiração militar. Assista o quanto quiser. Jon Bernthal (The Walking Dead) estrela esta saga de vingança baseada nos quadrinhos da Marvel.\r\n', 'Justiceiro.mp4', 'series_policiais5.png', 'justiceiro_info.png', 'series_policiais', 0),
(46, 'Game of Thrones', '2011', '+16', 'Game of Thrones conta a históra de um lugar onde uma força destruiu o equilíbrio das estações, há muito tempo. Em uma terra onde os verões podem durar vários anos e o inverno toda uma vida, as reivindicações e as forças sobrenaturais correm as portas do Reino dos Sete Reinos. A irmandade da Patrulha da Noite busca proteger o reino de cada criatura que pode vir de lá da Muralha, mas já não tem os recursos necessários para garantir a segurança de todos. Depois de um verão de dez anos, um inverno rigoroso promete chegar com um futuro mais sombrio. Enquanto isso, conspirações e rivalidades correm no jogo político pela disputa do Trono de Ferro, o símbolo do poder absoluto.', 'GameofThrones.mp4', 'series_fantasias1.png', 'got_info.png', 'series_fantasias', 0),
(47, 'Supernatural', '2005', '+13', 'Supernatural é uma série de TV norte-americana de fantasia sobrenatural transmitida originalmente pelo canal The CW. A trama acompanha os irmãos Sam e Dean Winchester que, há 20 anos, perderam a mãe em um trágico e misterioso acidente no qual as forças sobrenaturais estiveram envolvidas.', 'Supernatural.mp4', 'series_fantasias2.png', 'supernatural_info.png', 'series_fantasias', 0),
(48, 'Stranger Things', '2016', '+14', 'Em Stranger Things, quando Will (Noah Schnapp), um menino de 12 anos, desaparece misteriosamente, o xerife Jim Hopper (David Harbour) inicia uma operação para encontrá-lo. Enquanto isso, Mike (Finn Wolfhard), Dustin (Gaten Matarazzo) e Lucas (Caleb McLaughlin), melhores amigos de Will, decidem procurá-lo por conta própria. Mas as investigações acabam levando o grupo a experimentos secretos do governo e a uma peculiar menina perdida na floresta.', 'StrangerThings.mp4', 'series_fantasias3.png', 'strangerthings_info.png', 'series_fantasias', 0),
(49, 'The Originals', '2013', '+14', 'Um spin-off de The Vampire Diaries, que se passa em New Orleans. A série é centrada nos irmãos Mikaelson, que são conhecidos como os vampiros originais do mundo: Klaus (Joseph Morgan), Elijah (Daniel Gilles), e Rebekah (Claire Holt). Séculos atrás, eles prometeram ficar juntos para sempre e proteger uns aos outros. Agora, os laços familiares quebrados, tragédia e fome recaem como maldição àqueles que não cumpriram seus votos. ', 'TheOriginals.mp4', 'series_fantasias4.png', 'originals_info.png', 'series_fantasias', 0),
(50, 'The Flash', '2014', '+12', 'O investigador forense Barry Allen (Grant Gustin) sofre um acidente em seu laboratório: ele leva um banho de produtos químicos e, em seguida, é atingido por um raio. A partir disso, ele se torna capaz de canalizar os poderes do \"Campo de Velocidade\" e de se locomover com uma rapidez sobre-humana.', 'TheFlash.mp4', 'series_fantasias5.png', 'flash_info.png', 'series_fantasias', 0),
(51, 'The Walking Dead', '2010', '+16', 'Baseada em uma HQ, The Walking Dead conta a história de um grupo de sobreviventes, liderados pelo xerife Rick Grimes (Andrew Lincoln), após um apocalipse zumbi. Toda a população da Terra é infectada por um vírus misterioso que transforma os mortos em zumbis. ', 'TheWalkingDead.mp4', 'series_terror1.png', 'walking_info.png', 'series_terror', 0),
(52, 'American Horror Story', '2011', '+18', 'Baseada na lenda de Roanoke, narra a história do casal Shelby (Sarah Paulson / Lily Rabe) e Matt (Cuba Goodin Jr / André Holland), que se muda para uma casa no campo em Roanoke, Virginia, e descobrem uma série de acontecimentos estranhos nos arredores da residência.', 'AmericanHorrorStory.mp4', 'series_terror2.png', 'horror_info.png', 'series_terror', 0),
(53, 'IZombie', '2015', '+18', 'Olivia \"Liv\" Moore, uma médica residente de Seattle, é transformada em uma zumbi quando vai a uma festa em um barco. Para que consiga sobreviver, Liv come os cérebros de vítimas de homicídio cujos corpos são entregues ao necrotério.', 'IZombie.mp4', 'series_terror3.png', 'izombie_info.png', 'series_terror', 0),
(54, 'Outcast', '2016', '+18', 'Outcast acompanha Kyle Barnes, um homem cuja vida é atormentada desde a infância por possessões demoníacas que assolaram sua família. Já adulto e com a ajuda de um reverendo, ele tenta descobrir as mentiras por trás das manifestações sobrenaturais e o motivo de carregar peculiaridades especiais.\r\n', 'Outcast.mp4', 'series_terror4.png', 'outcast_info.png', 'series_terror', 0),
(55, 'The Outsider', '2020', '+18', 'Terry Maitland (Jason Bateman), treinador da liga infantil de baseball, professor de inglês e pai de duas filhas, é um dos homens mais queridos e respeitados da cidade em que vive. Mas, um dia, tudo muda quando ele é acusado de assassinar um menino de onze anos.', 'TheOutsider.mp4', 'series_terror5.png', 'outsider_info.png', 'series_terror', 0),
(56, 'O Beijo do Escorpião', '2014', '+6', 'A novela narra duas histórias centrais. Alice (Sara Matos) quer ficar com a vida de Rita (Dalila Carmo). Rita, por seu turno, quer incluir Alice na sua vida familiar feliz, que construiu com o marido, Fernando (Pedro Lima). Apesar das boas intenções, Rita não desconfia que a recém-encontrada irmã é um poço de maldade que só entrou na sua vida à procura de vingança e quer ocupar o seu lugar, destruindo tudo o que Rita construiu. Para o fazer, instala-se em sua casa, fazendo-se passar por um anjo.', 'O Beijo do Escorpião.mp4', 'tv_novelas1.png', 'escorpiao_info.png', 'novelas', 0),
(57, 'Ouro Verde', '2017', '+6', 'A novela conta a história de Jorge Monforte, dono do império Ouro Verde, uma empresa localizada na Amazônia que é referência no mercado agropecuário mundial. O bilionário adquire uma importante participação no Banco Brandão Ferreira Fonseca e conquista um assento no Conselho Administrativo da instituição.', 'Ouro Verde.mp4', 'tv_novelas2.png', 'ouroverde_info.png', 'novelas', 0),
(58, 'Amar Demais', '2020', '+6', 'A trama começa cerca de duas décadas atrás, quando Zeca aceita ser preso por um assassinato que não cometeu a troco de uma avultada quantia para salvar a mãe, que padece de uma terrível doença e cujos tratamentos são muito caros.', 'Amar Demais.mp4', 'tv_novelas3.png', 'amardemais_info.png', 'novelas', 0),
(59, 'Laços de Sangue', '2010', '+6', 'Tudo se inicia há 25 anos, quando duas irmãs são levadas na correnteza de um rio. O pai de ambas salva a mais velha, Inês, mas, acaba por falecer quando tenta resgatar a outra filha, cujo corpo nunca chega a aparecer. A mãe, que está grávida de um rapaz, assiste a toda a tragédia. Na actualidade, Inês (Diana Chaves) é uma jovem de personalidade forte, bondosa e sempre pronta a ajudar os outros. Licenciada em Gestão Hoteleira, é proprietária do restaurante M, em sociedade com a mãe. No entanto, algo a atormenta, uma vez que se sente culpada pelo falecimento da irmã.', 'Laços de Sangue.mp4', 'tv_novelas4.png', 'lacos_info.png', 'novelas', 0),
(60, 'Doce Fugitiva', '2006', '+6', 'Maria Estrela Santos (Rita Pereira), conhecida por Estrelinha, tem 22 anos e trabalha no café do pai, ao mesmo tempo que faz voluntariado num lar de acolhimento para crianças em situação de risco.', 'Doce Fugitiva.mp4', 'tv_novelas5.png', 'doce_info.png', 'novelas', 0),
(61, 'Friends', '1994', '+8', 'Ross, Rachel, Mônica, Chandler, Joey e Phoebe formam um grupo de seis amigos que lutam para se sobressair e progredir na competitiva vida de Manhattan. Seu humor inteligente e apoio mútuo incondicional fazem com sua amizade seja cada vez mais forte, superando assim todos os obstáculos que a vida lhes apresenta.', 'Friends.mp4', 'tv_comedia1.png', 'friends_info.png', 'tv_comedia', 0),
(62, 'Suits', '2011', '+12', 'Mike Ross (Patrick J. Adams) é um garoto que abandonou a faculdade de direito mas, brilhante como é, consegue uma entrevista com o respeitado Harvey Specter (Gabriel Macht), um dos melhores advogados de Manhattan. Quando percebe o talento nato e a memória fotográfica do garoto, Harvey o contrata e, juntos, eles formam uma dupla imbatível. Mesmo sendo um gênio, Mike ainda tem muito a aprender sobre o Direito. E mesmo sendo um advogado tão competende, Harvey irá aprender com sua nova dupla a ver seus clientes de outra maneira. ', 'Suits.mp4', 'tv_comedia2.png', 'suits_info.png', 'tv_comedia', 0),
(63, 'How I Met Your Mother', '2005', '+12', 'Em 2030, o arquiteto Ted Mosby (Josh Radnor) conta a história sobre como conheceu a mãe dos seus filhos. Ele volta no tempo para 2005, relembrando suas aventuras amorosas em Nova York e a busca pela mulher dos seus sonhos.', 'How I Met Your Mother.mp4', 'tv_comedia3.png', 'mother_info.png', 'tv_comedia', 0),
(64, 'The Big Bang Theory', '2007', '+12', 'Dois jovens gênios da física, Leonard (Johnny Galecki) e Sheldon Cooper (Jim Parsons), dividem um apartamento e são surpreendidos ao descobrir que a vizinha, Penny (Kaley Cuoco), é uma loira não tão inteligente. Leonard acredita que pode conquistar a jovem.', 'The Big Bang Theory .mp4', 'tv_comedia4.png', 'bigbang_info.png', 'tv_comedia', 0),
(65, 'Orange Is the New Black\r\n', '2013', '+14', 'Piper Chapman (Taylor Schilling) é uma mulher por volta de seus 30 anos que é sentenciada a 15 meses de prisão após ter cometido crimes para sua ex-namorada, a traficante Alex (Laura Prepon) — que não vê há mais de uma década. Piper troca a sua vida confortável de Nova York, com o noivo Larry (Jason Biggs), pelo macacão laranja, e cumpre sua sentença na Penitenciária Feminina de Litchfield. Para sobreviver, ela precisa aprender a conviver com as outras detentas, como Red (Kate Mulgrew), Nicky (Natasha Lyonne), Taystee (Danielle Brooks) e Crazy Eyes (Uzo Aduba). O que Piper não espera é encontrar a ex cumprindo pena no mesmo lugar. ', 'Orange Is The New Black.mp4', 'tv_comedia5.png', 'orange_info.png', 'tv_comedia', 0),
(66, 'Anthony Bourdain: Viagem ao Desconhecido', '2014', '+8', 'Anthony Bourdain está de volta ao 24Kitchen para a estreia de um novo programa. O chef vai levar os espectadores a lugares nunca antes explorados de algumas cidades e países espalhados pelo mundo em \"Anthony Bourdain: Viagem ao Desconhecido\", prometendo apresentar novas culturas e novos rituais de refeição.', 'Anthony Bourdain.mp4', 'tv_cozinha1.png', 'anthony_info.png', 'tv_cozinha', 0),
(67, 'Chef\'s Table', '2015', '+12', 'A série documental acompanha seis chefes internacionais, vindos dos Estados Unidos, da Itália, Argentina, Austrália e Suécia. Cada um deles apresenta a variedade e as preciosidades da cozinha de seus países, oferecendo um show de sabores em pratos que mais parecem obras de arte.', 'Chef\'s Table.mp4', 'tv_cozinha2.png', 'chefstable_info.png', 'tv_cozinha', 0),
(68, 'The Mind of a Chef', '2012', '+12', 'Essa é uma série de TV feita pela PBS, a televisão pública dos EUA. A proposta é acompanhar o processo criativo dos chefs de cozinha e suas influências, suas atividades no âmbito da cozinha e fora dela. Por ela é possível conhecer um pouco mais de chefs que são expoentes da gastronomia norte-americana. A narração é de Anthony Bourdain.', 'Mind of a Chef.mp4', 'tv_cozinha3.png', 'mind_info.png', 'tv_cozinha', 0),
(69, 'Ugly Delicious', '2018', '+12', 'O famoso chef David Chang leva seus amigos a uma caçada intercultural pelo mundo em busca de pratos que, aparências à parte, dão água boca. Assista o quanto quiser. Chefs famosos e artistas como Jimmy Kimmel, Nick Kroll e Ali Wong embarcam nesta aventura culinária indicada ao Emmy.', 'Ugly Delicious.mp4', 'tv_cozinha4.png', 'ugly_info.png', 'tv_cozinha', 0),
(70, 'The Taco Chronicles', '2019', '+12', 'A série explorará diferentes variedades de tacos que foram desenvolvidos ao longo de gerações e as histórias das pessoas por trás deles. De lojas de esquina a restaurantes sofisticados, o taco encontrou seu caminho em todos os cantos possíveis da indústria de alimentos e a série terá como objetivo mostrar essa diversidade.', 'The Taco Chronicles.mp4', 'tv_cozinha5.png', 'taco_info.png', 'tv_cozinha', 0),
(71, 'Toy Story', '1995', '+4', 'O aniversário do garoto Andy está chegando e seus brinquedos ficam nervosos, temendo que ele ganhe novos brinquedos que possam substituí-los. Liderados pelo caubói Woody, o brinquedo predileto de Andy, eles recebem Buzz Lightyear, o boneco de um patrulheiro espacial, que logo passa a receber mais atenção do garoto. Com ciúmes, Woody tenta ensiná-lo uma lição, mas Buzz cai pela janela. É o início da aventura do caubói, que precisa resgatar Buzz para limpar sua barra com os outros brinquedos.', 'Toy Story.mp4', 'animacaosugestoes_1.png', 'toystory_info.png', 'animacao_sugestoes', 0),
(72, 'Inside Out', '2015', '+4', 'Com a mudança para uma nova cidade, as emoções de Riley, que tem apenas 11 anos de idade, ficam extremamente agitadas. Uma confusão na sala de controle do seu cérebro deixa a Alegria e a Tristeza de fora, afetando a vida de Riley radicalmente.', 'Inside Out.mp4', 'animacaosugestoes_2.png', 'insideout_info.png', 'animacao_sugestoes', 0),
(73, 'Soul', '2020', '+6', 'Joe é um professor de música do ensino médio apaixonado por jazz, cuja vida não foi como ele esperava. Quando ele viaja a uma outra realidade para ajudar outra pessoa a encontrar sua paixão, ele descobre o verdadeiro sentido da vida.', 'Soul.mp4', 'animacaosugestoes_3.png', 'soul_info.png', 'animacao_sugestoes', 0),
(74, 'Zootopia', '2016', '+6', 'Em uma cidade de animais, uma raposa falante se torna uma fugitiva ao ser acusada de um crime que não cometeu. O principal policial do local, o incontestável coelho, sai em sua busca.', 'Zootopia.mp4', 'animacaosugestoes_4.png', 'zootopia_info.png', 'animacao_sugestoes', 0),
(75, 'UP: Altamente', '2009', '+6', 'Carl Fredricksen é um vendedor de balões que, aos 78 anos, está prestes a perder a casa em que sempre viveu com sua esposa, a falecida Ellie. Após um incidente, Carl é considerado uma ameaça pública e forçado a ser internado. Para evitar que isto aconteça, ele põe balões em sua casa, fazendo com que ela levante voo. Carl quer viajar para uma floresta na América do Sul, onde ele e Ellie sempre desejaram morar, mas descobre que um problema embarcou junto: Russell, um menino de 8 anos.', 'Up.mp4', 'animacaosugestoes_5.png', 'up_info.png', 'animacao_sugestoes', 0),
(76, 'Spider Man: Spider-Verse', '2018', '+6', 'Em Homem-Aranha no Aranhaverso, Miles Morales é um jovem negro do Brooklyn que se tornou o Homem-Aranha inspirado no legado de Peter Parker, já falecido. Entretanto, ao visitar o túmulo de seu ídolo em uma noite chuvosa, ele é surpreendido com a presença do próprio Peter, vestindo o traje do herói aracnídeo sob um sobretudo. A surpresa fica ainda maior quando Miles descobre que ele veio de uma dimensão paralela, assim como outras versões do Homem-Aranha.', 'Spider-Man - Miles Morales.mp4', 'animacaoacao_1.png', 'miles_info.png', 'animacao_acao', 0),
(77, 'Raya', '2021', '+6', 'Há muito tempo, no mundo de fantasia de Kumandra, humanos e dragões viviam juntos em harmonia. Mas quando uma força maligna ameaçou a terra, os dragões se sacrificaram para salvar a humanidade. Agora, 500 anos depois, o mesmo mal voltou e cabe a uma guerreira solitária, Raya, rastrear o lendário último dragão para restaurar a terra despedaçada e seu povo dividido.', 'Raya.mp4', 'animacaoacao_2.png', 'raya_info.png', 'animacao_acao', 0),
(78, 'Luca', '2021', '+6', 'Luca vive aventuras com seu novo melhor amigo, mas a diversão é ameaçada por um segredo: seu amigo é um monstro marinho de outro mundo que fica abaixo da superfície da água.', 'Luca.mp4', 'animacaoacao_3.png', 'luca_info.png', 'animacao_acao', 0),
(79, 'O Rei Leão', '1994', '+6', 'Este desenho animado da Disney mostra as aventuras de um leão jovem de nome Simba, o herdeiro de seu pai, Mufasa. O tio malvado de Simba, Oscar, planeja roubar o trono de Mufasa atraindo pai e filho para uma emboscada. Simba consegue escapar e somente Mufasa morre. Com a ajuda de seus amigos,Timon e Pumba, ele reaparece como adulto para recuperar sua terra, que foi roubada por seu tio Oscar.', 'Lion King.mp4', 'animacaoacao_4.png', 'reileao_info.png', 'animacao_acao', 0),
(80, 'Cars', '2006', '+6', 'Ao viajar para a Califórnia, o famoso carro de corridas Relâmpago McQueen se perde e vai parar em Radiator Springs, uma cidadezinha na Rota 66. Ele conhece novos amigos e aprende lições que mudam sua forma de encarar a vida.', 'Cars.mp4', 'animacaoacao_5.png', 'cars_info.png', 'animacao_acao', 0),
(81, 'The Witcher', '2019', '+15', 'Vesemir escapa à pobreza, tornando-se bruxo e matando monstros por dinheiro e glória. Mas quando surge uma nova ameaça, ele tem de enfrentar os demónios do passado.', 'Witcher.mp4', 'animacaodrama_1.png', 'witcher_info.png', 'animacao_drama', 0),
(82, 'Lightyear', '2022', '+6', 'A aventura de ação e ficção científica apresenta a história de origem definitiva de Buzz Lightyear - o herói que inspirou o brinquedo - apresentando o lendário Space Ranger que conquistaria gerações de fãs.', 'Lightyear.mp4', 'animacaodrama_2.png', 'lightyear_info.png', 'animacao_drama', 0),
(83, 'Rise of the Guardians', '2012', '+10', 'Jack Frost, um garoto que controla o inverno, se junta ao seleto time dos Guardiões Imortais para impedir Breu, o bicho-papão, de transformar todos os sonhos das crianças em pesadelo e usar seus poderes maquiavélicos para governar o mundo.', 'Rise of the Guardians.mp4', 'animacaodrama_3.png', 'rise_info.png', 'animacao_drama', 0),
(84, 'Onward', '2020', '+8', 'Em um mundo transformado, no qual as criaturas não dependiam mais da magia para viver, dois irmãos elfos recebem um cajado de bruxo de seu falecido pai, capaz de trazê-lo de volta à vida. Inexperientes com qualquer tipo de magia, Ian e Barley não conseguem executar o feitiço e acabam gerando uma criatura sem cabeça. Para passar mais um dia com seu pai, eles embarcam em uma jornada fantástica. Ao perceber a ausência dos filhos, sua mãe se une à uma lendária manticora para encontrá-los.', 'Onward.mp4', 'animacaodrama_4.png', 'onward_info.png', 'animacao_drama', 0),
(85, 'Ilha de Cães', '2018', '+8', 'Atari Kobayashi é um garoto japonês de 12 anos de idade. Ele mora na cidade de Megasaki, sob tutela do corrupto prefeito Kobayashi. O político aprova uma nova lei que proíbe os cachorros de morarem no local, fazendo com que todos os animais sejam enviados a uma ilha vizinha repleta de lixo. Mas o pequeno Atari não aceita se separar do cachorro Spots. Ele convoca os amigos, rouba um jato em miniatura e parte em busca de seu fiel amigo. A aventura vai transformar completamente a vida da cidade.', 'Isle of Dogs.mp4', 'animacaodrama_5.png', 'isledogs_info.png', 'animacao_drama', 0),
(86, 'Ron\'s Gone Wrong', '2021', '+8', 'Em um mundo em que robôs que andam, falam e estão conectados digitalmente se tornaram os melhores amigos das crianças, Ron, de 11 anos, descobre que seu amigo robô não funciona muito bem.', 'Rons Gone Wrong.mp4', 'animacaoficcao_1.png', 'rons_info.png', 'animacao_ficcao', 0),
(87, 'Wall-E', '2008', '+8', 'Após entulhar a Terra de lixo e poluir a atmosfera com gases tóxicos, a humanidade deixou o planeta e passou a viver em uma gigantesca nave. O plano era que o retiro durasse alguns poucos anos, com robôs sendo deixados para limpar o planeta. WALL-E é o último destes robôs, e sua vida consiste em compactar o lixo existente no planeta. Até que um dia surge repentinamente uma nave, que traz um novo e moderno robô: Eva. A princípio curioso, WALL-E se apaixona e resolve segui-la por toda a galáxia.', 'Wall-E.mp4', 'animacaoficcao_2.png', 'walle_info.png', 'animacao_ficcao', 0),
(88, 'The Incredibles: Os Super Heróis', '2004', '+8', 'Depois que o governo baniu o uso de superpoderes, o maior herói do planeta, o Sr. Incrível, vive agora uma vida normal e pacata com sua família. Apesar de feliz com a vida doméstica, o Sr. Incrível ainda sente falta dos tempos em que viveu como super-herói, e sua grande chance de entrar em ação novamente surge quando um velho inimigo volta a atacar. Só que agora ele terá que contar com a ajuda de toda a família para vencer o vilão!', 'The Incredibles.mp4', 'animacaoficcao_3.png', 'incredibles_info.png', 'animacao_ficcao', 0),
(89, 'Lego', '2014', '+6', 'Emmet é uma minifigura LEGO perfeitamente comum e seguidora das regras, que é erroneamente identificado como uma pessoa extraordinária, essencial para salvar o mundo. Ele é recrutado por uma irmandade de estranhos para uma jornada épica com a finalidade de deter um tirano, uma viagem para a qual Emmet está totalmente despreparado. Como companheiros dessa aventura, ele terá Vitrúvius, um velho místico, e a durona Lucy, que convoca o misterioso Batman, com quem compartilha uma história do passado.', 'Lego.mp4', 'animacaoficcao_4.png', 'lego_info.png', 'animacao_ficcao', 0),
(90, 'Space Jam: Um novo legado', '2021', '+12', 'Em Space Jam: Um Novo Legado, a inteligência artificial, Al G (Dom Cheadle) sequestra o filho de Lebron James e envia o lendário jogador dos Los Angeles Lakers para uma realidade paralela, onde vivem apenas os personagens de desenho animado da Warner Bros. Para resgatar o seu filho, ele precisará vencer uma partida épica de basquete contra superversões digitais das maiores estrelas da história da NBA e da WNBA. Para essa dura missão, King James terá a ajuda de Pernalonga, Patolino, Lola Bunny, dentre outros personagens consagrados de Looney Tunes.', 'Space Jam.mp4', 'animacaoficcao_5.png', 'spacejam_info.png', 'animacao_ficcao', 0),
(91, 'Rei da Comunicação', '2021', '+12', 'O Rei da Comunicação, André Sedin, presidente da Escola Superior de Comunicação Social, incentiva todos os alunos no início do novo ano letivo!', 'ReidaComunicação.mp4', 'filme_acao3.png', 'rei_info.png', 'filmes_acao', 0),
(92, 'Escsiano Misterioso', '2021', '+12', 'Acompanha a reportagem do início do ano letivo na ESCS e percebe o porquê de esta faculdade ser a melhor do país.', 'ESCSIANOMisterioso.mp4', 'filme_suspense5.png', 'escsiano_info.png', 'filmes_suspense', 0),
(93, 'ESCS Assombrada', '2021', '+12', 'Acompanha o dia-a-dia na Escola Superior de Comunicação Social e surpreende-te com a quantidade de coisas que podes aprender nesta fantástica escola!', 'ESCSAssombrada.mp4', 'filme_terror2.png', 'escsassombrada_info.png', 'filmes_terror', 0),
(94, 'LAB 3D: A Sequela', '2021', '+12', 'Assiste a um excelente trabalho desempenhado por um dos alunos da ESCS na cadeira de Laboratório 3D.', 'Lab3D.mp4', 'filme_animacao2.png', 'lab3d_info.png', 'filmes_animacao', 0);

-- --------------------------------------------------------

--
-- Estrutura da tabela `login`
--

CREATE TABLE `login` (
  `id` int(2) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  `usertype` varchar(50) NOT NULL DEFAULT 'user'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Extraindo dados da tabela `login`
--

INSERT INTO `login` (`id`, `username`, `password`, `usertype`) VALUES
(1, 'Nuno Palma', 'melhorprofessor', 'Nuno Palma');

-- --------------------------------------------------------

--
-- Estrutura da tabela `temas`
--

CREATE TABLE `temas` (
  `id` int(11) NOT NULL,
  `text` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Extraindo dados da tabela `temas`
--

INSERT INTO `temas` (`id`, `text`) VALUES
(1, 'Suspense'),
(2, 'Aventura'),
(3, 'Animação'),
(4, 'Terror');

--
-- Índices para tabelas despejadas
--

--
-- Índices para tabela `filmes`
--
ALTER TABLE `filmes`
  ADD PRIMARY KEY (`id`);

--
-- Índices para tabela `login`
--
ALTER TABLE `login`
  ADD PRIMARY KEY (`id`);

--
-- Índices para tabela `temas`
--
ALTER TABLE `temas`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `filmes`
--
ALTER TABLE `filmes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=123;

--
-- AUTO_INCREMENT de tabela `login`
--
ALTER TABLE `login`
  MODIFY `id` int(2) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT de tabela `temas`
--
ALTER TABLE `temas`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
